version: '3.9'

services:
  # database:
  #   image: postgres
  #   container_name: tutorial
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin
  #     - POSTGRES_DB=todolistdb
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  nodeapp:
    image: danilotaveiranavega/todolist-backend:latest
    restart: always
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://todolist_admin:todolist_senha@todolist-db.cyfddsnqioox.us-east-1.rds.amazonaws.com:5432/todolistdb

  reactapp:
    image: danilotaveiranavega/todolist-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nodeapp

volumes:
  pgdata:
    driver: local
