version: '3.9'

services:
  nodeapp:
    build: ./back  # ← Faz build do backend localmente
    restart: always
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://todolist_admin:todolist_senha@todolist-db.cyfddsnqioox.us-east-1.rds.amazonaws.com:5432/todolistdb

  reactapp:
    build: ./front  # ← Faz build do frontend com o proxy via NGINX
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nodeapp
